name: CI/CD Pipeline for restr0-backend

on:
  push:
    branches:
      - main    # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main    # Trigger the workflow on PRs targeting the 'main' branch

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the correct version of Node.js

      # Step 3: Cache Node.js dependencies to speed up subsequent builds
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Run tests (Optional, if you have a test suite)
      # - name: Run tests
      #   run: npm test  # Ensure you have a proper test suite

      # # Step 6: Lint the code (Optional)
      # - name: Lint the code
      #   run: npm run lint  # Ensure you have a linting script

      # Step 7: Build the project (Optional, if needed)
      - name: Build project (if required)
        run: npm run build  # Uncomment this if you need a build step

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3  # Update to use v3

      # Step 2: Set up SSH with private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key from GitHub Secrets

      # Step 3: Deploy to VPS (restr0-backend)
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@168.231.122.13"
            # Navigate to the project directory
            cd /var/www/Restro/restro-back && 

            # Pull the latest changes from GitHub
            git pull origin main && 

            # Install dependencies (if new dependencies are added)
            npm install && 

            # Build the project (if necessary)
            npm run build && 

            # Check if the app is running, reload it if possible; otherwise, restart
            pm2 show restro-backend > /dev/null 2>&1 && \
            pm2 reload restro-backend --watch --name restro-backend || \
            pm2 restart restro-backend && \
            
            # Save the PM2 process list for persistence
            pm2 save"
