name: CI Pipeline for Dev Branch

on:
  push:
    branches:
      - main    # Trigger the workflow on push to the 'dev' branch
  pull_request:
    branches:
      - main    # Trigger the workflow on PRs targeting the 'dev' branch

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the correct version of Node.js you are using

      # Step 3: Cache Node.js dependencies to speed up subsequent builds
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Run tests
      - name: Run tests
        run: npm test  # Runs your test suite

      # Step 6: Lint the code
      - name: Lint the code
        run: npm run lint  # Optional: Only if you have a linting script

      # Step 7: Build the project (Optional)
      - name: Build project
        run: npm run build  # Optional: Run this if you have a build step like TypeScript
